remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: BriGap
description: The Workshop on Bridges and Gaps between Formal and Computational Linguistics

show_downloads: false

github:
  is_user_page: false
