remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: BriGap-2
description: The Second Workshop on Bridges and Gaps between Formal and Computational Linguistics

show_downloads: false
